### ISSUE TITLE
decrypt performance question

### ISSUE THREAD

**Issue by Feofilov** [brainfoolong/php-ascon#1]
I experimented with images encryption. In my case decrypt worked extremely slowly. Perhaps I'm missing something? 
I tried to decrypt a 250 kb image, it took more than 20 seconds.

System characteristics:
RAM: 16GB
CPU: M1 8-core
PHP: php:8.1.18-fpm

Here's my code:

```
public function uploadImage(UploadImageRequest $request): JsonResponse
    {
        $start = microtime(true);

        foreach ($request->images as $image) {
            // Image is about 254 KB
            $bytesArray = unpack('C*', $image->get());
            $decrypted = Ascon::decrypt(
                Ascon::hash('mystrongpassword', 'Ascon-Xof', 16),
                array_slice($bytesArray, -16, 16, true),
                'test',
                array_splice($bytesArray,0, -16),
            );
            dd(microtime(true) - $start); // 20s

            $image = Image::make(gzuncompress(Ascon::byteArrayToStr($decrypted)));
            $image->save(Storage::disk('public')->path('/test.jpg'));
        }

        return response()->json([
            'execution_time' => microtime(true) - $start,
        ], 200);
    }
```

**Comment by brainfoolong** [comment]
Hi. Yes, it's that slow by design of the algorithm. It's to prevent brute force attacks. It's not the PHP implementation that make it that slow.
The native C implementation is about 20-40% faster, on the same machine compared to PHP.

**Comment by Feofilov** [comment]
> Hi. Yes, it's that slow by design of the algorithm. It's to prevent brute force attacks. It's not the PHP implementation that make it that slow. The native C implementation is about 20-40% faster, on the same machine compared to PHP.

Thanks for the answer! Please tell me if I understood correctly that this does not overload the CPU etc? And it's just it's just supposed to work slowly? And is it probably better to choose some other algorithm for images encryption/decryption? (sorry for stupid questions)

**Comment by brainfoolong** [comment]
If it will overload your CPU depends on your system. This algorithm is probably not what you search for, wenn you want to encrypt whole files fast. This algo is designed for raw short messages to be interchangeable on all different hardware and software languages.
I am not the developer of the algorithm, I just implemented it in PHP and JS.
